---
- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ user.name }}/{{ dotfiles.destination }} accept_hostkey=yes update=no key_file="/home/{{ user.name }}/.ssh/id_rsa" version="{{ hostname | default('master') }}"
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: "/home/{{ user.name }}/.dotfiles/install"
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
