---
- name: Install hostsctl
  aur: name=hostsctl
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Push hostsctl config
  template: src=hostsctl.conf.j2 dest=/etc/hostsctl.conf

- name: Update hostsctl
  command: hostsctl update
