---
- name: Install dictd
  pacman:
    name: dictd
    state: present

- name: Install GNU Collaborative International Dictionary of English
  aur:
    name: dict-gcide
    skip_pgp: yes
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install WordNet database
  aur:
    name: dict-wn
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install Moby thesaurus
  aur:
    name: dict-moby-thesaurus
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur
