---
- name: Install pass
  pacman:
    name: pass
    state: present

- name: Install pass-otp
  pacman:
    name: pass-otp
    state: present

- name: Install rofi-pass
  pacman:
    name: rofi-pass
    state: present
  tags:
    - rofi

- name: Install pass-update
  aur:
    name: pass-update
    skip_pgp_check: yes
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install pwgen-passphrase
  aur:
    name: pwgen-passphrase
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur
