---
- name: Install I3-gaps
  aur:
    name: i3-gaps
    user: dpendolino
    use: yay

- name: Install i3 related apps
  pacman:
    name:
      - i3blocks
      - i3lock
      - i3status
      - polybar
    state: present

- name: Install py3status
  pacman: name=py3status state=present

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF

- include: rofi.yml
