---
- include: beets.yml
- include: abcde.yml
- include: xfburn.yml
- include: imagemagick.yml
- include: inkscape.yml
- include: gimp.yml
- include: gthumb.yml
- include: feh.yml
- include: imv.yml
- include: mcomix.yml
- include: teiler.yml
- include: flac2all.yml
- include: darktable.yml
- include: qcode.yml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - opus-tools
    state: present

- name: Install Metadata Anonymisation Toolkit
  aur:
    name: mat2
    skip_pgp_check: yes
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - aur
    - mat

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present
