---
- name: Install Dnsmasq
  pacman: name=dnsmasq state=present

- name: Configure resolvconf to use dnsmasq
  template: src=resolvconf.conf.j2 dest=/etc/resolvconf.conf

- name: Run update resolvconf
  shell:
    cmd: resolvconf -u

- name: Copy dnsmasq configuration file
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf
  notify:
    - restart dnsmasq

- name: Enable and start dnsmasq
  service: name=dnsmasq.service enabled=yes state=started
